image:
  repository: ghcr.io/azrtydxb/solder
  tag: v0.1.11
  pullPolicy: IfNotPresent

replicaCount: 2
leaderElection: true

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
