---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - services
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - impersonate
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - statefulsets
    verbs:
      - list
      - watch
  - apiGroups:
      - solder.io
    resources:
      - applications
      - repositories
      - revisions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - solder.io
    resources:
      - applications/finalizers
      - repositories/finalizers
      - revisions/finalizers
    verbs:
      - update
  - apiGroups:
      - solder.io
    resources:
      - applications/status
      - repositories/status
      - revisions/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - solder.io
    resources:
      - healthchecks
    verbs:
      - get
      - list
      - watch
