apiVersion: solder.io/v1alpha1
kind: Revision
metadata:
  name: payments-8c51af2
  namespace: default
spec:
  applicationRef:
    name: payments
  source:
    repositoryRef:
      name: platform
    revision: 8c51af2
    path: apps/payments
    render:
      type: kustomize
  desiredStateHash: example
