apiVersion: sync.kuvryn.io/v1alpha1
kind: Repository
metadata:
  name: platform
  namespace: default
spec:
  type: git
  git:
    url: ssh://git@github.com/acme/platform.git
    revision: main
    auth:
      secretRef:
        name: platform-git
  applicationConfigPaths:
    - .solder.yaml
  pollInterval: 60s
