apiVersion: v1
kind: Service
metadata:
  name: {{ include "kuvryn-sync.fullname" . }}-metrics
  labels:
    app.kubernetes.io/name: {{ include "kuvryn-sync.name" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "kuvryn-sync.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: https
      port: 8443
      targetPort: 8443
