{{- if .Values.webhookReceiver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kuvryn-sync.fullname" . }}-receiver
  labels:
    app.kubernetes.io/name: {{ include "kuvryn-sync.name" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "kuvryn-sync.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: 9292
{{- end }}
